COMMANDS = ["HELP", "SAUCE", "ALEATORIO", "ANIMEOMANGA", "JAPONABIERTO",
            "KALISE", "RANDOMMEDIA", "YENAEURO", "EUROAYEN", "LEVELUP",
            "LEVELUPALL", "TEST", "TESTAÑO", "LOG", "MVP", "PODIO", "LOGS",
            "EXPORT", "ME", "BACKFILL", "PUNTOS", "UNDO", "REMLOG", "ORDENARLOGS",
            "PROGRESO", "KOMGAINFO", "SUBSCRIBE", "UNSUBSCRIBE", "BUSCARMANGA"]

CATEGORIES = ["INMERSION", "KOTOBA", "TESTS", "EXTRAS", "MANGA"]
