COMMANDS = ["HELP", "SAUCE", "YOJI", "ANIMEOMANGA", "JAPONABIERTO",
            "KALISE", "RANDOMMEDIA", "YENAEURO", "EUROAYEN", "LEVELUP",
            "LEVELUPALL", "TEST", "TESTAÑO", "LOG", "MVP", "PODIO", "LOGS",
            "EXPORT", "ME", "BACKFILL", "PUNTOS", "UNDO", "REMLOG", "ORDENARLOGS",
            "PROGRESO", "KOMGAINFO", "SUBSCRIBE", "UNSUBSCRIBE", "BUSCARMANGA", "TIME", "ACCENT", "GRAMMAR", "ANISON", "EDITLOG", "RANKING", "LASTLOG", "ManabeSTATS", "LOGROS", "CONSTANCIA"]

CATEGORIES = ["INMERSION", "KOTOBA", "TESTS", "EXTRAS", "MANGA"]
